### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by NickCaplinger** [blitmap/lua-utf8-simple#1]
Hi @blitmap ,

This looks like a nice little UTF-8 utility, but I don't want to use it because it does not include a license. Could you attach a LICENSE file? If you don't particularly care, MIT is great: http://opensource.org/licenses/MIT

**Comment by blitmap** [comment]
Sure thing, I'll attach it in an hour or so - I'm not on the computer I
usually git from :-)

**Comment by blitmap** [comment]
Okay, LICENSE added :-)  I do love the MIT license...  sorry that took a
while tonight was busy.

Anyway, good luck to you friend :-)

**Comment by blitmap** [comment]
Hah, I did not realize this was an issue opened on github - I thought you sent me an email.  Silly github notifications.  Anyway, LICENSE added.  :-)

**Comment by NickCaplinger** [comment]
Hi blitmap,

I wasn't sure where to find your email so this was the next best thing. I did see your other emails, so that's good.

Anyway, thanks for adding a license so quickly! I appreciate your work here.

Cheers,
Nick

**Comment by blitmap** [comment]
It just makes me feel warm and gooey inside knowing this project has been helping people, haha.  I didn't think it would get this much attention.  Lua 5.3 came out with it's built-in utf8 library and I've been wondering if I should backport it in pure Lua for 5.2, 5.1, and 5.0.  I figure people have been using my library for the older Lua's :-)
